# Generated by Django 2.1.3 on 2018-11-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'About us', 'verbose_name_plural': 'About us'},
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Contact Us', 'verbose_name_plural': 'Contact Us'},
        ),
        migrations.AlterModelOptions(
            name='firstpageprojects',
            options={'verbose_name': 'First Page Projects', 'verbose_name_plural': 'First Page Projects'},
        ),
        migrations.AlterField(
            model_name='contactus',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='google_maps_embed_html',
            field=models.TextField(blank=True, null=True, verbose_name='google maps embeded html'),
        ),
    ]
