# Generated by Django 2.1.3 on 2018-11-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181125_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='google_maps_embed_html',
        ),
        migrations.AddField(
            model_name='contactus',
            name='google_maps_src',
            field=models.URLField(blank=True, null=True, verbose_name='google maps src'),
        ),
    ]
