# Generated by Django 2.1.3 on 2018-12-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_aboutus_about_us_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ordering',
            field=models.IntegerField(default=1, verbose_name='ordering'),
        ),
    ]
