# Generated by Django 2.1.3 on 2018-11-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181125_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='about_us_text',
            field=models.TextField(blank=True, null=True, verbose_name='about us text'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='aduren_reel_vimeo_url',
            field=models.URLField(blank=True, null=True, verbose_name='Aduren Reel Vimeo URL'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='artists',
            field=models.ManyToManyField(blank=True, related_name='artists', to='core.Artist', verbose_name='artists'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='clients',
            field=models.ManyToManyField(blank=True, related_name='clients', to='core.Client', verbose_name='clients'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='founders',
            field=models.ManyToManyField(blank=True, related_name='founders', to='core.Founder', verbose_name='founders'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='prizes',
            field=models.ManyToManyField(blank=True, related_name='prizes', to='core.Prize', verbose_name='prizes'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='services', to='core.Service', verbose_name='services'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='slide_show_pictures',
            field=models.ManyToManyField(blank=True, related_name='slide_show_pictures', to='core.SlideShowPicture', verbose_name='slide show pictures'),
        ),
    ]
