# Generated by Django 2.1.3 on 2018-11-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20181125_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='about_us_short',
            field=models.TextField(blank=True, null=True, verbose_name='about us short description'),
        ),
    ]
