# Generated by Django 2.1.3 on 2018-11-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_aboutus_about_us_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='artists/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='award',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='prizes/'),
        ),
        migrations.AlterField(
            model_name='founder',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='founders/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='image'),
        ),
    ]
